default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['KINEDU_DATABASE_USERNAME'] %>
  password: <%= ENV['KINEDU_DATABASE_PASSWORD'] %>
  socket: <%= ENV['KINEDU_SOCKET'] %>

development:
  <<: *default
  database: <%= ENV['KINEDU_DEVELOPMENT_DATABASE'] %>

test:
  <<: *default
  database: <%= ENV['KINEDU_TEST_DATABASE'] %>

production:
  <<: *default
  database: <%= ENV['KINEDU_PRODUCTION_DATABASE'] %>
